KUBE_VERSION: 1.11.3
ADM_WORKDIR: $PWD
ADM_PKIDIR: $PWD/pki/
ADM_TMP: "{{ ADM_PKIDIR }}'/*'"
GO_VERSION: 1.10.3
ADM_OS: linux-amd64
KUBERNETES_PUBLIC_ADDRESS: 
ADM_CA: "{{ ADM_PKIDIR }}/pki-ca"
ADM_KUBECONFIGDIR: "{{ ADM_WORKDIR }}/config"
ADM_TMP: "{{ ADM_KUBECONFIGDIR }}'/*'"
ENCRYPTION_KEY: $(head -c 32 /dev/urandom | base64)
ETCD_VERSION: 3.3.5
ETCD_NAME: etcd
RUNC_VERSION: 1.0.0-rc5
CRICTL_VERSION: 1.0.0-beta.0
CNI_PLUGINS_VERSION: 0.6.0
CONTAINERD_VERSION: 1.1.2
