kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "{{ KHW_CONFIG }}kube-proxy.kubeconfig"
mode: "iptables"
clusterCIDR: "{{ KHW_NET_CIDR }}/{{ KHW_NET_CIDR_MASK }}"
