- hosts: controller
  become: true
  roles:
    - create_directories
    - install_packages
    - certs
    - etcd
    - download_kubectl
    - role: 'kubernetes/controller'
    - del_tmp_directories

- hosts: workers
  become: true
  roles:
    - create_directories
    - install_packages
    - certs
    - etcd
    - download_kubectl
    - role: 'kubernetes/worker'
    - del_tmp_directories
