- hosts: localhost  
  become: true
  roles:
    - create_directories
    - install_packages
    - certs
    - etcd
    - download_kubectl
    - role: 'kubernetes/controller'
    - role: 'kubernetes/worker'
#    - del_tmp_directories
