- hosts: localhost  
  become: true
  roles:
    - create_directories
    - download_binaries
    - install_packages
    - certs
    - etcd
    - role: 'kubernetes/controller'
    - role: 'kubernetes/worker'
