- template:
    src: .templates/10-bridge.conf
    dest: /etc/cni/net.d/10-bridge.conf
    owner: root
    group: root
    mode: 0644

- template:
    src: .templates/99-loopback.conf
    dest: /etc/cni/net.d/99-loopback.conf
    owner: root
    group: root
    mode: 0644

- template:
    src: .templates/kube-proxy-config.yaml
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml
    owner: root
    group: root
    mode: 0644

- template:
    src: .templates/kubelet-config.yaml
    dest: /var/lib/kubelet/kubelet-config.yaml
    owner: root
    group: root
    mode: 0644
