#### KUBE-PROXY CONF

- debug:
    msg: "generating kube-proxy configs"

- name: kubectl config set-cluster
  shell: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority="{{ ADM_CA }}/ca.pem" --embed-certs=true --server=https://{{ KUBERNETES_PUBLIC_ADDRESS }}:6443 --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-proxy.kubeconfig"

- name: kubectl config set-credentials
  shell: kubectl config set-credentials system:kube-proxy --client-certificate="{{ ADM_KEY }}/kube-proxy.pem" --client-key="{{ ADM_KEY }}/kube-proxy-key.pem" --embed-certs=true --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-proxy.kubeconfig"

- name: kubectl config set-context
  shell: kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-proxy --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-proxy.kubeconfig"

- name: kubectl config use-context
  shell: kubectl config use-context default --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-proxy.kubeconfig"

- name: move kube-proxy.kubeconfig
  shell: mv {{ ADM_KUBECONFIGDIR }}kube-proxy.kubeconfig /var/lib/kube-proxy/kubeconfig


##### ADMIN CONFIG

- debug:
    msg: "generating admin configs"

- name: kubectl config set-cluster
  shell: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority="{{ ADM_CA }}/ca.pem"  --embed-certs=true --server=https://127.0.0.1:6443  --kubeconfig="{{ ADM_KUBECONFIGDIR }}admin.kubeconfig"

- name: kubectl config set-credentials
  shell: kubectl config set-credentials admin --client-certificate="{{ ADM_KEY }}/admin.pem" --client-key={{ ADM_KEY }}/admin-key.pem --embed-certs=true --kubeconfig="{{ ADM_KUBECONFIGDIR }}admin.kubeconfig"

- name: kubectl config set-context default
  shell: kubectl config set-context default --cluster=kubernetes-the-hard-way --user=admin --kubeconfig="{{ ADM_KUBECONFIGDIR }}admin.kubeconfig"

- name: kubectl config use-context default
  shell: kubectl config use-context default --kubeconfig="{{ ADM_KUBECONFIGDIR }}admin.kubeconfig"

- name: move admin.kubeconfig
  shell: mv {{ ADM_KUBECONFIGDIR }}admin.kubeconfig /var/lib/kubelet/kubeconfig
