- name: daemon-reload
  systemd: daemon_reload=yes

- name: start kube-proxy
  systemd:
    name: kube-proxy.service
    state: started
    enabled: yes

- name: start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes