- name: daemon-reload
  systemd: daemon_reload=yes

- name: start kube-proxy
  systemd:
    name: kube-proxy.service
    state: restarted
    enabled: yes

- name: start kubelet
  systemd:
    name: kubelet.service
    state: restarted
    enabled: yes

- name: start containerd
  systemd:
    name: containerd.service
    state: restarted
    enabled: yes