kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca/ca.pem"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.32.0.10"
podCIDR: "10.0.0.0/16"
runtimeRequestTimeout: "15m"
tlsCertFile: "/etc/kubernetes/pki/key/kubelet.pem"
tlsPrivateKeyFile: "/etc/kubernetes/pki/key/kubelet.pem-key"
