- name: get_cfssl
  shell: wget -q --https-only --no-dns-cache https://pkg.cfssl.org/{{ CFSSL_VERSION }}/cfssl_{{ KHW_ARCH }} --output-document=/bin/cfssl
- name: get_cfssljson
  shell: wget -q --https-only --no-dns-cache https://pkg.cfssl.org/{{ CFSSL_VERSION }}/cfssljson_{{ KHW_ARCH }} --output-document=/bin/cfssljson
- name: chmod
  shell: chmod +x /bin/cfssl /bin/cfssljson
