- name: swap off
  shell: swapoff -a

- name: swap off step 2
  shell: sed -i.bak -r 's/(.+ swap .+)/#\1/' /etc/fstab

- name: modprobe
  shell: modprobe br_netfilter

- sysctl:
    name: vm.oom_kill_allocating_task
    value: '2'
    state: present

- sysctl:
    name: vm.oom_dump_tasks
    value: '1'
    state: present

- sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present

- sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
