 - name: install packages for deb
   apt:
     name: "{{ packages }}"
     state: present
   vars:
     packages:
     - libseccomp2
     - aufs-dkms
     - socat
     - conntrack
     - ipset
   when: ansible_facts['distribution'] == "Debian"

 - name: install packages for yum
   yum:
     name: "{{ packages }}"
     state: present
   vars:
     packages:
     - libseccomp
     - socat
     - conntrack
     - ipset
   when: ansible_facts['distribution'] == "CentOS"
