- name: download kube-apiserver
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ KUBE_VERSION }}/bin/linux/amd64/kube-apiserver
    dest: "{{ KHW_PREFIX }}bin/kube-apiserver"
    mode: 0755

- name: download kube-controller-manager
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ KUBE_VERSION }}/bin/linux/amd64/kube-controller-manager
    dest: "{{ KHW_PREFIX }}bin/kube-controller-manager"
    mode: 0755

- name: download kube-scheduler
  get_url:  
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ KUBE_VERSION }}/bin/linux/amd64/kube-scheduler
    dest: "{{ KHW_PREFIX }}bin/kube-scheduler"
    mode: 0755
