- name: download GO
  unarchive:
    src: https://dl.google.com/go/go{{ GO_VERSION }}.{{ KHW_ARCH }}.tar.gz
    dest: "{{ KHW_PREFIX }}opt"
    remote_src: yes
    mode: 0755

- name: export PATH
  shell: export PATH=$PATH:"{{ KHW_PREFIX }}"opt/go/bin

- name: export GO PATH
  shell: export GOPATH=$HOME/go

- name: download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ KUBE_VERSION }}/bin/linux/amd64/kubectl
    dest: "{{ KHW_PREFIX }}bin/kubectl"
    mode: 0755
