- name: download etcd
  unarchive:
    src: "https://github.com/coreos/etcd/releases/download/v{{ ETCD_VERSION }}/etcd-v{{ ETCD_VERSION }}-{{ KHW_ARCH }}.tar.gz"
    dest: "{{ KHW_PREFIX }}bin"
    remote_src: yes
    mode: 0755
- name: mv etcd binaries
  shell: "mv {{ KHW_PREFIX }}bin/etcd-v{{ ETCD_VERSION }}-{{ KHW_ARCH }}/etcd* {{ KHW_PREFIX }}bin/"
