- name: downlad_etcd
  include: downlad_etcd.yaml

- name: create_etcd_directories
  include: create_etcd_directories.yaml

#- name: copy_etcd_certs
#  include: copy_etcd_certs.yaml

- name: copy_etcd_service
  include: copy_etcd_service.yaml

- name: start_etcd
  include: start_etcd.yaml
