- name: Create directory
  file: path=/etc/kubernetes/pki/csr state=directory

- template:
    src: kubelet-csr.json.j2
    dest: "/etc/kubernetes/pki/csr/kubelet-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: admin-csr.json.j2
    dest: "/etc/kubernetes/pki/csr/admin-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kube-controller-manager-csr.json.j2
    dest: "/etc/kubernetes/pki/csr/kube-controller-manager-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kube-proxy-csr.json.j2
    dest: "/etc/kubernetes/pki/csr/kube-proxy-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kube-scheduler-csr.json.j2
    dest: "/etc/kubernetes/pki/csr/kube-scheduler-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kubernetes-csr.json.j2
    dest: "/etc/kubernetes/pki/csr/kubernetes-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: service-account-csr.json.j2
    dest: "/etc/kubernetes/pki/csr/service-account-csr.json"
    owner: root
    group: root
    mode: 0644
