- name: Create directory
  file: path={{ KHW_CSR }} state=directory

- template:
    src: kubelet-csr.json.j2
    dest: "{{ KHW_CSR }}kubelet-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: admin-csr.json.j2
    dest: "{{ KHW_CSR }}admin-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kube-controller-manager-csr.json.j2
    dest: "{{ KHW_CSR }}kube-controller-manager-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kube-proxy-csr.json.j2
    dest: "{{ KHW_CSR }}kube-proxy-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kube-scheduler-csr.json.j2
    dest: "{{ KHW_CSR }}kube-scheduler-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: kubernetes-csr.json.j2
    dest: "{{ KHW_CSR }}kubernetes-csr.json"
    owner: root
    group: root
    mode: 0644

- template:
    src: service-account-csr.json.j2
    dest: "{{ KHW_CSR }}service-account-csr.json"
    owner: root
    group: root
    mode: 0644
