---
- name: gen ca
  shell: cfssl gencert -initca "{{ ADM_PKIDIR }}ca-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}ca"

- name: gen admin cert
  shell: cfssl gencert -ca="{{ ADM_PKIDIR }}ca.pem" -ca-key="{{ ADM_PKIDIR }}ca-key.pem" -config="{{ ADM_PKIDIR }}ca-config.json" -profile=kubernetes "{{ ADM_PKIDIR }}admin-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}admin"

- name: gen client cert
  shell: cfssl gencert -ca="{{ ADM_PKIDIR }}ca.pem" -ca-key="{{ ADM_PKIDIR }}ca-key.pem" -config="{{ ADM_PKIDIR }}ca-config.json" -hostname={{ hostname }},{{ EXTERNAL_IP }},{{ INTERNAL_IP }} -profile=kubernetes "{{ ADM_PKIDIR }}{{ hostname }}-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}{{ hostname }}"

- name: gen controller manager cert
  shell: cfssl gencert -ca="{{ ADM_PKIDIR }}ca.pem" -ca-key="{{ ADM_PKIDIR }}ca-key.pem" -config="{{ ADM_PKIDIR }}ca-config.json" -profile=kubernetes "{{ ADM_PKIDIR }}kube-controller-manager-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}kube-controller-manager"

- name: gen kube-proxy key
  shell: cfssl gencert -ca="{{ ADM_PKIDIR }}ca.pem" -ca-key="{{ ADM_PKIDIR }}ca-key.pem" -config="{{ ADM_PKIDIR }}ca-config.json" -profile=kubernetes "{{ ADM_PKIDIR }}kube-proxy-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}kube-proxy"

- name: gen scheduler client key
  shell: cfssl gencert -ca="{{ ADM_PKIDIR }}ca.pem" -ca-key="{{ ADM_PKIDIR }}ca-key.pem" -config="{{ ADM_PKIDIR }}ca-config.json" -profile=kubernetes "{{ ADM_PKIDIR }}kube-scheduler-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}kube-scheduler"

- name: gen kubeapi key
  shell: cfssl gencert -ca="{{ ADM_PKIDIR }}ca.pem" -ca-key="{{ ADM_PKIDIR }}ca-key.pem" -config="{{ ADM_PKIDIR }}ca-config.json" -hostname=10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,{{ KUBERNETES_PUBLIC_ADDRESS }},127.0.0.1,kubernetes.default -profile=kubernetes "{{ ADM_PKIDIR }}kubernetes-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}kubernetes"

- name: gen service account key
  shell: cfssl gencert -ca="{{ ADM_PKIDIR }}ca.pem" -ca-key="{{ ADM_PKIDIR }}ca-key.pem" -config="{{ ADM_PKIDIR }}ca-config.json" -profile=kubernetes "{{ ADM_PKIDIR }}service-account-csr.json" | cfssljson -bare "{{ ADM_PKIDIR }}service-account"

