- name: get_cfssl
  get_url:
    url: https://pkg.cfssl.org/{{ CFSSL_VERSION }}/cfssl_{{ KHW_ARCH }}
    dest: "{{ KHW_PREFIX }}bin/cfssl"
    mode: 0540

- name: get_cfssljson
  get_url:
    url: https://pkg.cfssl.org/{{ CFSSL_VERSION }}/cfssljson_{{ KHW_ARCH }}
    dest: "{{ KHW_PREFIX }}bin/cfssljson"
    mode: 0540
