- file:
    path: "{{ KHW_CA }}"
    state: directory
    mode: 0755

- name: Get CA
  copy:
    src: "{{ KHW_LOCAL_CFSSL }}ca/ca.pem"
    dest: "{{ KHW_CA }}ca.pem"
    owner: root
    group: root
    mode: 0644

- name: Get CA key
  copy:
    src: "{{ KHW_LOCAL_CFSSL }}ca/ca-key.pem"
    dest: "{{ KHW_CA }}ca-key.pem"
    owner: root
    group: root
    mode: 0644

- name: Get CA config
  copy:
    src: "{{ KHW_LOCAL_CFSSL }}ca/ca-config.json"
    dest: "{{ KHW_CA }}ca-config.json"
    owner: root
    group: root
    mode: 0644

- name: Get CA for CentOS
  copy:
    src: "{{ KHW_LOCAL_CFSSL }}ca/ca.pem"
    dest: "/etc/pki/ca-trust/source/anchors/kubernetes.crt"
    owner: root
    group: root
    mode: 0644
  when: ansible_facts['distribution'] == "CentOS"

- name: Get CA for Debian
  copy:
    src: "{{ KHW_LOCAL_CFSSL }}ca/ca.pem"
    dest: "/usr/local/share/ca-certificates/kubernetes.crt"
    owner: root
    group: root
    mode: 0644
  when: ansible_facts['distribution'] == "Debian"

- name: Update trusted CA for Debian
  shell: update-ca-certificates
  when: ansible_facts['distribution'] == "Debian"

- name: Update trusted CA for CentOS
  shell: update-ca-trust force-enable && update-ca-trust extract
  when: ansible_facts['distribution'] == "CentOS"
