- name: copy ca cert
  copy:
    src: "{{ ADM_CA }}ca.pem"
    dest: /var/lib/kubernetes/ca.pem
    owner: root
    group: root
    mode: 0644

- name: copy ca key
  copy:
    src: "{{ ADM_CA }}ca-key.pem"
    dest: /var/lib/kubernetes/ca-key.pem
    owner: root
    group: root
    mode: 0644

- name: copy kubernetes cert
  copy:
    src: "{{ ADM_CA }}kubernetes.pem"
    dest: /var/lib/kubernetes/kubernetes.pem
    owner: root
    group: root
    mode: 0644

- name: copy kubernetes key
  copy:
    src: "{{ ADM_CA }}kubernetes-key.pem"
    dest: /var/lib/kubernetes/kubernetes-key.pem
    owner: root
    group: root
    mode: 0644

- name: copy service-account cert
  copy:
    src: "{{ ADM_CA }}service-account.pem"
    dest: /var/lib/kubernetes/service-account.pem
    owner: root
    group: root
    mode: 0644

- name: copy service-account key
  copy:
    src: "{{ ADM_CA }}service-account-key.pem"
    dest: /var/lib/kubernetes/service-account-key.pem
    owner: root
    group: root
    mode: 0644

- name: copy {{ hostname }} cert
  copy:
    src: "{{ ADM_CA }}{{ hostname  }}.pem"
    dest: /var/lib/kubelet/{{ hostname }}.pem
    owner: root
    group: root
    mode: 0644

- name: copy {{ inventory_hostname  }} key
  copy:
    src: "{{ ADM_CA }}{{ inventory_hostname  }}-key.pem"
    dest: /var/lib/kubelet/{{ inventory_hostname  }}-key.pem
    owner: root
    group: root
    mode: 0644
