##### KUBE-CONTROLLER-MANAGER CONFIG

- debug:
    msg: "generating kube-controller-manager configs"

- name: kubectl config set-cluster
  shell: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority="{{ ADM_CA }}ca.pem" --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-controller-manager.kubeconfig"

- name: kubectl config set-credentials
  shell: kubectl config set-credentials system:kube-controller-manager --client-certificate="{{ ADM_PKIDIR }}kube-controller-manager.pem" --client-key="{{ ADM_PKIDIR }}kube-controller-manager-key.pem" --embed-certs=true --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-controller-manager.kubeconfig"

- name: kubectl config set-context
  shell: kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-controller-manager --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-controller-manager.kubeconfig"

- name: kubectl config use-context default
  shell: kubectl config use-context default --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-controller-manager.kubeconfig"

- name: move kube-controller-manager.kubeconfig
  shell: mv {{ ADM_KUBECONFIGDIR }}kube-controller-manager.kubeconfig /var/lib/kubernetes/


##### KUBE-SCHEDULER CONFIG

- debug:
    msg: "generating kube-scheduler configs"

- name: kubectl config set-cluster
  shell: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority="{{ ADM_CA }}ca.pem" --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-scheduler.kubeconfig"

- name: kubectl config set-credentials
  shell: kubectl config set-credentials system:kube-scheduler --client-certificate="{{ ADM_PKIDIR }}kube-scheduler.pem" --client-key="{{ ADM_PKIDIR }}kube-scheduler-key.pem" --embed-certs=true --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-scheduler.kubeconfig"

- name: kubectl config set-context
  shell: kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-scheduler --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-scheduler.kubeconfig"

- name: kubectl config use-context
  shell: kubectl config use-context default --kubeconfig="{{ ADM_KUBECONFIGDIR }}kube-scheduler.kubeconfig"

- name: move kube-scheduler.kubeconfig
  shell: mv {{ ADM_KUBECONFIGDIR }}kube-scheduler.kubeconfig /var/lib/kubernetes/
