- name: download binaries
  include: download_binaries.yaml

- name: copy certs
  include: copy_certs.yaml

- name: copy systemd template
  include: copy_systemd_template.yaml

- name: copy configs
  include: copy_configs.yaml

- name: start services
  include: start_services.yaml

