- name: create directories
  include: create_directories.yaml

- name: download binaries
  include: download_binaries.yaml

#- name: copy certs
#  include: copy_certs.yaml

- name: gen certs
  include: gen_certs.yaml

- name: copy systemd template
  include: copy_systemd_template.yaml

- name: gen configs
  include: gen_configs.yaml

- name: start services
  include: start_services.yaml

