[metrics]
  address = "0.0.0.0:1365"
[plugins]
  [plugins.cri.containerd]
    snapshotter = "overlayfs"
    [plugins.cri.containerd.default_runtime]
      runtime_type = "io.containerd.runtime.v1.linux"
      runtime_engine = "{{ KHW_PREFIX }}bin/runc"
      runtime_root = ""
    [plugins.cri.containerd.untrusted_workload_runtime]
      runtime_type = "io.containerd.runtime.v1.linux"
      runtime_engine = "{{ KHW_PREFIX }}bin/runsc"
      runtime_root = "/run/containerd/runsc"
{% if ( (KHW_UNSECURE_REGISTRY is defined) and (KHW_UNSECURE_REGISTRY != "")) %}
    [plugins.cri.registry.mirrors."local.insecure-registry.io"]
      endpoint = [" {{ KHW_UNSECURE_REGISTRY }}"]
{% endif %}
