 - name: install packages
   apt:
     name: "{{ packages }}"
     state: installed
   vars:
     packages:
     - libseccomp2
     - aufs-dkms
     - socat
     - conntrack
     - ipset
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
